//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.15 at 11:12:51 PM MSK 
//


package tr.kir.akhram;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tr.kir.akhram package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tr.kir.akhram
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetTrainingResponse }
     * 
     */
    public GetTrainingResponse createGetTrainingResponse() {
        return new GetTrainingResponse();
    }

    /**
     * Create an instance of {@link TrainingSoap }
     * 
     */
    public TrainingSoap createTrainingSoap() {
        return new TrainingSoap();
    }

    /**
     * Create an instance of {@link GetTrainingRequest }
     * 
     */
    public GetTrainingRequest createGetTrainingRequest() {
        return new GetTrainingRequest();
    }

    /**
     * Create an instance of {@link ExerciseSoap }
     * 
     */
    public ExerciseSoap createExerciseSoap() {
        return new ExerciseSoap();
    }

    /**
     * Create an instance of {@link TrainingSetSoap }
     * 
     */
    public TrainingSetSoap createTrainingSetSoap() {
        return new TrainingSetSoap();
    }

}
